# Generated by Django 5.1.3 on 2024-12-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_name', models.CharField(max_length=500)),
                ('Amount', models.IntegerField()),
                ('Category', models.CharField(max_length=200)),
                ('Date', models.DateField()),
            ],
        ),
    ]
